# Generated by Django 3.2.7 on 2021-09-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20210917_1537'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requesttable',
            table='request_form',
        ),
        migrations.AlterModelTable(
            name='responsetable',
            table='response_form',
        ),
    ]
